// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.BlockchainBalances.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Blockchain.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Blockchain
    {
        [EnumMember(Value = "Btc")]
        Btc,
        [EnumMember(Value = "Eth")]
        Eth
    }
    internal static class BlockchainEnumExtension
    {
        internal static string ToSerializedValue(this Blockchain? value)
        {
            return value == null ? null : ((Blockchain)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Blockchain value)
        {
            switch( value )
            {
                case Blockchain.Btc:
                    return "Btc";
                case Blockchain.Eth:
                    return "Eth";
            }
            return null;
        }

        internal static Blockchain? ParseBlockchain(this string value)
        {
            switch( value )
            {
                case "Btc":
                    return Blockchain.Btc;
                case "Eth":
                    return Blockchain.Eth;
            }
            return null;
        }
    }
}
